# Generated by Django 3.2.7 on 2021-09-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'مدیر'), ('customer', 'مشتری'), ('employee', 'کارمند')], default='customer', max_length=600),
        ),
    ]
